name: Dependabot
version: 2
on:
  manual-schedule:
    - cron: "0 0 * * *"
  workflow-dispatch:
updates:
  # Update npm and Yarn dependencies
  - package-ecosystem: "npm"
    directory: "/" # Root directory of the repository
    schedule:
      interval: "daily" # Check for updates daily
    open-pull-requests-limit: 5

  # Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/" # Root directory of the repository
    schedule:
      interval: "daily" # Check for updates daily
    open-pull-requests-limit: 5