name: Basic Workflow
on:
    push:
        branches:
        - main
jobs:
    do-things:
        name: Do Things
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          run: echo "This file will be stored as an artifact, in the Future :)"
        - name: Sending an error code 
          run: |
           echo "Failed to Publish Artificat "
           exit 1
