name: Basic Workflow
on:
    push:
        branches:
        - master
jobs:
    do-things:
        name: Do Things
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: echo "This file will be stored as an artifact, in the Future :)"
