name: call_Repo_Checkout_Workflow
on:
  workflow_dispatch:
    inputs:
      runner:
        description: Choice Example
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
env:
  GITHUB_WORKFLOW_REF: ${{ github.repository }}
  GITHUB_REF_NAME: ${{ github.ref_name }}

jobs:
  debug-validation:
    name: Debug Validation of URL With ENV
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Print URL With ENV
        run:  "${{ github.repository }}/.github/workflows/checkout-job.yaml@$${{ github.ref_name }}"
        shell: bash
  call-reusable-workflow:
    uses: ${{ github.repository }}/.github/workflows/checkout-job.yaml@$${{ github.ref_name }}
    with:
      git-repo: https://github.com/${{ github.repository }}.git
      git-branch: ${{ github.head_ref || github.ref_name }}
      git-runner: ${{ inputs.runner }}