name: Call-checkout-test
    on:
    workflow_dispatch:
        inputs:
            runner:
                description: Choice Example
                required: true
                default: warning
                type: choice
                options:
                    - windows-latest
                    - ubuntu-latest
        

job:
    runs-on: ${{inputs.runner}}
    centralized-job:
        uses: ./.github/workflows/checkout-job.yaml
        with:
            git-repo: ${{ github.repository }}
            git-branch: ${{ github.ref_name }}
            git-rummer: ${{inputs.runner}}
