name: Checkout Git Repo and Branch
on:
  workflow_call:
    inputs:
      git-runner:
        description: Runner
        required: true
        type: string

jobs:
  checkout-git-repo-and-branch:
    runs-on: ${{ inputs.git-runner }}
    steps:
      - name: Clone repository
        run: |
          echo "Cloning repository: "
          git clone --depth=1 --branch=https://github.com/${{ github.repository }}/.github/workflows/checkout-job.yaml@${{ github.ref_name }} repo
          cd repo
          echo "Repository checked out successfully."
        shell: bash






