name: Checkout Git Repo and Branch
on:
  workflow_call:
    inputs:
      git-runner:
        description: Runner
        required: true
        type: string

jobs:
  checkout-git-repo-and-branch:
    runs-on: ${{ inputs.git-runner }}
    steps:
      - name: Clone Linux repository
        if: ${{ inputs.git-runner == 'ubuntu-latest' }}
        run: |
          echo "Cloning repository: "
          echo https://github.com/${{ github.repository }}
          git clone --depth=1 --branch=${{ github.ref_name }} https://github.com/${{ github.repository }} -v
          cd $(basename ${{ github.repository }} .git) # Change to the cloned repo directory
          ls -al
          echo "Repository checked out successfully."
        shell: bash

      - name: Clone Windows repository
        if: ${{ inputs.git-runner == 'windows-latest' }}
        run: |
          Write-Host "Cloning repository: "
          Write-Host https://github.com/${{ github.repository }}
          git clone --depth=1 --branch=${{ github.ref_name }} https://github.com/${{ github.repository }}
          cd $(Split-Path -Leaf ${{ github.repository }}) # Change to the cloned repo directory
          Get-ChildItem
          Write-Host "Repository checked out successfully."
        shell: powershell








