name: call_Repo_Checkout_Workflow
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Choice Example'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'windows-latest'
          - 'ubuntu-latest'

jobs:
  debug-validation:
    name: Debug Validation of URL With ENV
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Print URL With ENV
        run: echo "${{ github.repository }}/.github/workflows/checkout-job.yaml@${{ github.ref_name }}"
        shell: bash

  call-reusable-workflow:
    uses: ./.github/workflows/checkout-job.yaml
    with:
      git-runner: ${{ inputs.runner }}
