name: call_Repo_Checkout_Workflow
on:
  workflow_dispatch:
    inputs:
      runner:
        description: Choice Example
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - windows-latest
          - ubuntu-latest

jobs:
  call-reusable-workflow:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Call reusable workflow
        uses: ${{GITHUB_SERVER_URL}}/repos/${{ github.repository }}/actions/workflows/checkout-job.yaml@${{GITHUB_REF}}
        with:
          git_repo: https://github.com/${{ github.repository }}.git
          git_branch: ${{ github.head_ref || github.ref_name }}
          git_runner: ${{ inputs.runner }}