name: call_Repo_Checkout_Workflow
on:
  workflow_dispatch:
    inputs:
      runner:
        description: Choice Example
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - windows-latest
          - ubuntu-latest

jobs:
  call-reusable-workflow:
    uses: IdoHemed12/Frok-github-actions-exercises/.github/workflows/checkout-job.yaml@main
    with:
      git-repo: https://github.com/${{ github.repository }}.git
      git-branch: ${{ github.head_ref || github.ref_name }}
      git-runner: ${{ inputs.runner }}