name: Continuous Integration & Delivery
on:
  pull_request:
  workflow_dispatch:
    branches: [main]
defaults:
  run:
    shell: /bin/ash
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: golang_app
    steps:
      - name: Path Setup
        id: go-paths
        working-directory: ${{github.workspace}}
        run: |
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
          echo "gocache=$(go env GOCACHE)" >> $GITHUB_OUTPUT          
      - name: checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-paths.outputs.gomodcache }}
            ${{ steps.go-paths.outputs.gocache }}
          key: ${{ runner.os }}-gomodcache-${{ hashFiles('**/go.sum') }}        
      - name: get-dependencies
        run: go mod download
      - name: build
        run: go build
      - name: Rubn lint
        uses: golangci/golangci-lint-action@v3
        with:
          wokring-directory: golang_app
      - name: Run tests
        run: go test -v ./...
      - name: Upload Artificat
        uses: actions/upload-artifact@v4.6.2
        with:
          name: golang_app
          path: golang_app/app
