name: using-defaults
    on:
        push:
            branches:
                - feature/defaults
    jobs:
        first-job:
            rus-on: ubuntu-latest
            steps:
                -name: create a srv directory
                run: mkdir src
                shell: bash
                -name: use python
                run: import os' print("This is a python shell script using os module " + os.getcwd())'
                shell: python")'
                working-directory: src
        second-job:
            runs-on: ubuntu-latest
            steps:
                -name: Create a dst directoy
                run: mkdir dst
                shell: bash
                working-directory: src..\
                -name: use bash
                run: echo "This is the dst directory $(pwd../dst)"
                working-directory: dst
                