name: Dependabot-auto-Pull-Request
# Set up automatic PRs for Dependabot
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Dependabot
        uses: dependabot/dependabot-action@v2
        with:
          package-manager: 'npm_and_yarn' # Change this to your package manager (e.g., pip, maven, etc.)
          directory: '/' # Root directory of the repository
          open-pull-requests-limit: 5 # Limit the number of open PRs