version: 2
on:
  schedule:
    - cron: "0 11 * * *"  # This cron syntax means once a day at 11 AM

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): update"