on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v1
        with:
          package-ecosystem: "github-actions"
          directory: "/"
          schedule-interval: "daily"
          open-pull-requests-limit: 10
          target-branch: "main" 