name: Dependent Jobs
on:
  push:
    branches:
      - main
jobs:
  first-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: dump job information
        env:
          CONTEXT_ITEM: ${{ toJson(job) }}
        run: echo $CONTEXT_ITEM
      - name: sleep-job
        run: sleep 20
        shell: bash

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: dump job information
        env:
          CONTEXT_ITEM: ${{ toJson(job) }}
        run: echo $CONTEXT_ITEM
      - name: sleep-job
        run: sleep 20
        shell: bash