# Disabled Workflow
name: Print Workflow Variables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print all environment variables to a JSON file
        run: |
          # Create a JSON object from environment variables
          jq -n env > workflow-env.json
        shell: bash

      - name: Upload environment variables as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: workflow-variables
          path: workflow-env.json
